#ifndef _BOILERPLATE_DIALOG_H
#define _BOILERPLATE_DIALOG_H

#define ID_DLG 99

#define IDE_LEFT 100
#define IDE_RIGHT 101
#define IDE_INTERVAL 102
#define IDB_TEST 103
#define IDB_STARTSTOP 104

#endif // _BOILERPLATE_DIALOG_H

